export const START_ANNOTATION = '@@app/START_ANNOTATION';
export const CANCEL_ANNOTATION = '@@app/CANCEL_ANNOTATION';
export const SET_ANNOTATION = '@@app/SET_ANNOTATION';
export const CREATE_ANNOTATION = '@@app/CREATE_ANNOTATION';
export const CREATE_ANNOTATION_SUCCESS = '@@app/CREATE_ANNOTATION_SUCCESS';
