export const SHOW_PROJECT = 'SHOW_PROJECT';
export const SHOW_PROJECT_SUCCESS = 'SHOW_PROJECT_SUCCESS';

export const CREATE_IMAGE = 'CREATE_IMAGE';
export const CREATE_IMAGE_SUCCESS = 'CREATE_IMAGE_SUCCESS';
export const SELECT_IMAGE = 'SELECT_IMAGE';

export const UPDATE_BASICS = 'UPDATE_BASICS';
export const UPDATE_BASICS_SUCCESS = 'UPDATE_BASICS_SUCCESS';