
// Material

export const FETCH_MATERIAL = '@@app/FETCH_MATERIAL';
export const UPDATE_MATERIAL = '@@app/UPDATE_MATERIAL';
export const CREATE_MATERIAL = '@@app/CREATE_MATERIAL';
export const FETCH_MATERIAL_SUCCESS = '@@app/FETCH_MATERIAL_SUCCESS';
export const UPDATE_MATERIAL_SUCCESS = '@@app/UPDATE_MATERIAL_SUCCESS';
export const CREATE_MATERIAL_SUCCESS = '@@app/CREATE_MATERIAL_SUCCESS';

// Material types

export const FETCH_MATERIAL_TYPES = '@@app/FETCH_MATERIAL_TYPES';
export const FETCH_MATERIAL_TYPES_SUCCESS = '@@app/FETCH_MATERIAL_TYPES_SUCCESS';

// Colors

export const FETCH_COLORS = '@@app/FETCH_COLORS';
export const FETCH_COLORS_SUCCESS = '@@app/FETCH_COLORS_SUCCESS';

// Currencies

export const FETCH_CURRENCIES = '@@app/FETCH_CURRENCIES';
export const FETCH_CURRENCIES_SUCCESS = '@@app/FETCH_CURRENCIES_SUCCESS';

// Care Labels

export const FETCH_CARE_LABELS = '@@app/FETCH_CARE_LABELS';
export const FETCH_CARE_LABELS_SUCCESS = '@@app/FETCH_CARE_LABELS_SUCCESS';

// Suppliers

export const FETCH_SUPPLIERS = '@@app/FETCH_SUPPLIERS';
export const FETCH_SUPPLIERS_SUCCESS = '@@app/FETCH_SUPPLIERS_SUCCESS';
export const NEW_SUPPLIER = '@@app/NEW_SUPPLIER';
export const SWITCH_SUPPLIER = '@@app/SWITCH_SUPPLIER';
