
// Material

export const FETCH_MATERIAL = 'FETCH_MATERIAL';
export const UPDATE_MATERIAL = 'UPDATE_MATERIAL';
export const FETCH_MATERIAL_SUCCESS = 'FETCH_MATERIAL_SUCCESS';
export const UPDATE_MATERIAL_SUCCESS = 'UPDATE_MATERIAL_SUCCESS';

// Material types

export const FETCH_MATERIAL_TYPES = 'FETCH_MATERIAL_TYPES';
export const FETCH_MATERIAL_TYPES_SUCCESS = 'FETCH_MATERIAL_TYPES_SUCCESS';

// Colors

export const FETCH_COLORS = 'FETCH_COLORS';
export const FETCH_COLORS_SUCCESS = 'FETCH_COLORS_SUCCESS';
