export const FETCH_PROJECT = '@@app/FETCH_PROJECT';
export const UPDATE_PROJECT = '@@app/UPDATE_PROJECT';
export const FETCH_PROJECT_SUCCESS = '@@app/FETCH_PROJECT_SUCCESS';
export const UPDATE_PROJECT_SUCCESS = '@@app/UPDATE_PROJECT_SUCCESS';

export const SWITCH_COMPONENT = '@@app/SWITCH_COMPONENT';
export const FETCH_COMPONENTS = '@@app/FETCH_COMPONENTS';
export const UPDATE_COMPONENT = '@@app/UPDATE_COMPONENT';
export const CREATE_COMPONENT = '@@app/CREATE_COMPONENT';
export const DELETE_COMPONENT = '@@app/DELETE_COMPONENT';
export const FETCH_MATERIAL_COST = '@@app/FETCH_MATERIAL_COST';
export const FETCH_COMPONENTS_SUCCESS = '@@app/FETCH_COMPONENTS_SUCCESS';
export const UPDATE_COMPONENT_SUCCESS = '@@app/UPDATE_COMPONENT_SUCCESS';
export const CREATE_COMPONENT_SUCCESS = '@@app/CREATE_COMPONENT_SUCCESS';
export const DELETE_COMPONENT_SUCCESS = '@@app/DELETE_COMPONENT_SUCCESS';
export const FETCH_MATERIAL_COST_SUCCESS = '@@app/FETCH_MATERIAL_COST_SUCCESS';

export const SWITCH_INSTRUCTION = '@@app/SWITCH_INSTRUCTION';
export const FETCH_INSTRUCTIONS = '@@app/FETCH_INSTRUCTIONS';
export const UPDATE_INSTRUCTION = '@@app/UPDATE_INSTRUCTION';
export const CREATE_INSTRUCTION = '@@app/CREATE_INSTRUCTION';
export const DELETE_INSTRUCTION = '@@app/DELETE_INSTRUCTION';
export const FETCH_INSTRUCTIONS_SUCCESS = '@@app/FETCH_INSTRUCTIONS_SUCCESS';
export const UPDATE_INSTRUCTION_SUCCESS = '@@app/UPDATE_INSTRUCTION_SUCCESS';
export const CREATE_INSTRUCTION_SUCCESS = '@@app/CREATE_INSTRUCTION_SUCCESS';
export const DELETE_INSTRUCTION_SUCCESS = '@@app/DELETE_INSTRUCTION_SUCCESS';

export const FETCH_MEASUREMENTS = '@@app/FETCH_MEASUREMENTS';
export const UPDATE_MEASUREMENTS = '@@app/UPDATE_MEASUREMENTS';
export const DELETE_MEASUREMENTS = '@@app/DELETE_MEASUREMENTS';
export const CREATE_MEASUREMENT_NAME = '@@app/CREATE_MEASUREMENT_NAME';
export const CREATE_MEASUREMENT_GROUP = '@@app/CREATE_MEASUREMENT_GROUP';

export const FETCH_MEASUREMENTS_SUCCESS = '@@app/FETCH_MEASUREMENTS_SUCCESS';
export const UPDATE_MEASUREMENTS_SUCCESS = '@@app/UPDATE_MEASUREMENTS_SUCCESS';
export const DELETE_MEASUREMENTS_SUCCESS = '@@app/DELETE_MEASUREMENTS_SUCCESS';
export const CREATE_MEASUREMENT_NAME_SUCCESS =
  '@@app/CREATE_MEASUREMENT_NAME_SUCCESS';
export const CREATE_MEASUREMENT_GROUP_SUCCESS =
  '@@app/CREATE_MEASUREMENT_GROUP_SUCCESS';
