export const LIST_PROJECTS = 'LIST_PROJECTS';
export const LIST_PROJECTS_SUCCESS = 'LIST_PROJECTS_SUCCESS';
export const LIST_PROJECTS_ERROR = 'LIST_PROJECTS_ERROR';
export const SHOW_PROJECT = 'SHOW_PROJECT';
export const SHOW_PROJECT_SUCCESS = 'SHOW_PROJECT_SUCCESS';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const ARCHIVE_PROJECT = 'ARCHIVE_PROJECT';
export const ARCHIVE_PROJECT_SUCCESS = 'ARCHIVE_PROJECT_SUCCESS';

export const UPDATE_BASICS = 'UPDATE_BASICS';
export const UPDATE_BASICS_SUCCESS = 'UPDATE_BASICS_SUCCESS';

export const CHANGE_SECTION = 'CHANGE_SECTION';
