export const PLACEHOLDER = `${process.env.ASSET_HOST}/19jCEX4.jpg`;

export const ADD_ANNOTATION = '@@app/ADD_ANNOTATION';
export const CANCEL_ANNOTATION = '@@app/CANCEL_ANNOTATION';
export const SET_ANNOTATION = '@@app/SET_ANNOTATION';
export const CREATE_ANNOTATION = '@@app/CREATE_ANNOTATION';
export const CREATE_ANNOTATION_SUCCESS = '@@app/CREATE_ANNOTATION_SUCCESS';
