export const FETCH_COMPONENTS = '@@app/FETCH_COMPONENTS';
export const FETCH_COMPONENTS_SUCCESS = '@@app/FETCH_COMPONENTS_SUCCESS';

export const UPDATE_COMPONENT = '@@app/UPDATE_COMPONENT';
export const UPDATE_COMPONENT_SUCCESS = '@@app/UPDATE_COMPONENT_SUCCESS';

export const CREATE_COMPONENTS = '@@app/CREATE_COMPONENTS';
export const CREATE_COMPONENTS_SUCCESS = '@@app/CREATE_COMPONENTS_SUCCESS';

export const DELETE_COMPONENT = '@@app/DELETE_COMPONENT';
export const DELETE_COMPONENT_SUCCESS = '@@app/DELETE_COMPONENT_SUCCESS';

export const SELECT_MATERIAL = '@@app/SELECT_MATERIAL';

export const VIEW = { list: 'Materials', create: 'Create new material' };
