export const SWITCH_COMPONENT = '@@app/SWITCH_COMPONENT';

export const FETCH_COMPONENTS = '@@app/FETCH_COMPONENTS';
export const FETCH_COMPONENTS_SUCCESS = '@@app/FETCH_COMPONENTS_SUCCESS';

export const UPDATE_COMPONENT = '@@app/UPDATE_COMPONENT';
export const UPDATE_COMPONENT_SUCCESS = '@@app/UPDATE_COMPONENT_SUCCESS';

export const CREATE_COMPONENT = '@@app/CREATE_COMPONENT';
export const CREATE_COMPONENT_SUCCESS = '@@app/CREATE_COMPONENT_SUCCESS';

export const DELETE_COMPONENT = '@@app/DELETE_COMPONENT';
export const DELETE_COMPONENT_SUCCESS = '@@app/DELETE_COMPONENT_SUCCESS';
