
// Invites

export const SEND_INVITE = '@@app/SEND_INVITE';
export const SEND_INVITE_SUCCESS = '@@app/SEND_INVITE_SUCCESS';

export const FETCH_INVITES = '@@app/FETCH_INVITES';
export const FETCH_INVITES_SUCCESS = '@@app/FETCH_INVITES_SUCCESS';

export const UPDATE_INVITE = '@@app/UPDATE_INVITE';
export const UPDATE_INVITE_SUCCESS = '@@app/UPDATE_INVITE_SUCCESS';

export const CANCEL_INVITE = '@@app/CANCEL_INVITE';
export const CANCEL_INVITE_SUCCESS = '@@app/CANCEL_INVITE_SUCCESS';

// Collaborators

export const FETCH_COLLABORATORS = '@@app/FETCH_COLLABORATORS';
export const FETCH_COLLABORATORS_SUCCESS = '@@app/FETCH_COLLABORATORS_SUCCESS';

export const UPDATE_COLLABORATOR = '@@app/UPDATE_COLLABORATOR';
export const UPDATE_COLLABORATOR_SUCCESS = '@@app/UPDATE_COLLABORATOR_SUCCESS';

export const REMOVE_COLLABORATOR = '@@app/REMOVE_COLLABORATOR';
export const REMOVE_COLLABORATOR_SUCCESS = '@@app/REMOVE_COLLABORATOR_SUCCESS';

// Other

export const FETCH_ROLE_TYPES = '@@app/FETCH_ROLE_TYPES';
export const FETCH_ROLE_TYPES_SUCCESS = '@@app/FETCH_ROLE_TYPES_SUCCESS';