export const SEND_INVITE = '@@app/SEND_INVITE';
export const SEND_INVITE_SUCCESS = '@@app/SEND_INVITE_SUCCESS';

export const FETCH_INVITES = '@@app/FETCH_INVITES';
export const FETCH_INVITES_SUCCESS = '@@app/FETCH_INVITES_SUCCESS';

export const UPDATE_INVITE = '@@app/UPDATE_INVITE';
export const UPDATE_INVITE_SUCCESS = '@@app/UPDATE_INVITE_SUCCESS';

export const CANCEL_INVITE = '@@app/CANCEL_INVITE';
export const CANCEL_INVITE_SUCCESS = '@@app/CANCEL_INVITE_SUCCESS';
