export const LIST_PROJECTS = 'LIST_PROJECTS';
export const LIST_PROJECTS_SUCCESS = 'LIST_PROJECTS_SUCCESS';
export const LIST_PROJECTS_ERROR = 'LIST_PROJECTS_ERROR';
export const SHOW_BASICS = 'SHOW_BASICS';
export const SHOW_BASICS_SUCCESS = 'SHOW_BASICS_SUCCESS';
