export const FETCH_MEASUREMENTS = '@@app/FETCH_MEASUREMENTS';
export const UPDATE_MEASUREMENTS = '@@app/UPDATE_MEASUREMENTS';
export const DELETE_MEASUREMENTS = '@@app/DELETE_MEASUREMENTS';
export const CREATE_MEASUREMENT_NAME = '@@app/CREATE_MEASUREMENT_NAME';
export const CREATE_MEASUREMENT_GROUP = '@@app/CREATE_MEASUREMENT_GROUP';

export const FETCH_MEASUREMENTS_SUCCESS = '@@app/FETCH_MEASUREMENTS_SUCCESS';
export const UPDATE_MEASUREMENTS_SUCCESS = '@@app/UPDATE_MEASUREMENTS_SUCCESS';
export const DELETE_MEASUREMENTS_SUCCESS = '@@app/DELETE_MEASUREMENTS_SUCCESS';
export const CREATE_MEASUREMENT_NAME_SUCCESS =
  '@@app/CREATE_MEASUREMENT_NAME_SUCCESS';
export const CREATE_MEASUREMENT_GROUP_SUCCESS =
  '@@app/CREATE_MEASUREMENT_GROUP_SUCCESS';

export const UNFOCUS_MEASUREMENTS = '@@app/UNFOCUS_MEASUREMENTS';
export const FOCUS_MEASUREMENT_NAME = '@@app/FOCUS_MEASUREMENT_NAME';
export const FOCUS_MEASUREMENT_GROUP = '@@app/FOCUS_MEASUREMENT_GROUP';
