export const LIST_PROJECTS = 'LIST_PROJECTS';
export const LIST_PROJECTS_SUCCESS = 'LIST_PROJECTS_SUCCESS';
export const LIST_PROJECTS_ERROR = 'LIST_PROJECTS_ERROR';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const FILE_PROJECT = 'FILE_PROJECT';
export const FILE_PROJECT_SUCCESS = 'FILE_PROJECT_SUCCESS';

