export const LIST_PROJECTS = 'LIST_PROJECTS';
export const LIST_PROJECTS_SUCCESS = 'LIST_PROJECTS_SUCCESS';
export const LIST_PROJECTS_ERROR = 'LIST_PROJECTS_ERROR';
export const SHOW_PROJECT = 'SHOW_PROJECT';
export const SHOW_PROJECT_SUCCESS = 'SHOW_PROJECT_SUCCESS';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const CHANGE_SECTION = 'CHANGE_SECTION';
