export const SWITCH_COMMENT = '@@app/SWITCH_COMMENT';

export const WRITE_REPLY = '@@app/WRITE_REPLY';
export const WRITE_COMMENT = '@@app/WRITE_COMMENT';
export const EDIT_COMMENT = '@@app/EDIT_COMMENT';

export const CREATE_COMMENT = '@@app/CREATE_COMMENT';
export const CREATE_COMMENT_SUCCESS = '@@app/CREATE_COMMENT_SUCCESS';

export const UPDATE_COMMENT = '@@app/UPDATE_COMMENT';
export const UPDATE_COMMENT_SUCCESS = '@@app/UPDATE_COMMENT_SUCCESS';

export const DELETE_COMMENT = '@@app/DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = '@@app/DELETE_COMMENT_SUCCESS';

export const START_ANNOTATION = '@@app/START_ANNOTATION';
export const CREATE_ANNOTATION = '@@app/CREATE_ANNOTATION';
export const CREATE_ANNOTATION_SUCCESS = '@@app/CREATE_ANNOTATION_SUCCESS';
