export const CREATE_COMMENT = '@@app/CREATE_COMMENT';
export const CREATE_COMMENT_SUCCESS = '@@app/CREATE_COMMENT_SUCCESS';

export const UPDATE_COMMENT = '@@app/UPDATE_COMMENT';
export const UPDATE_COMMENT_SUCCESS = '@@app/UPDATE_COMMENT_SUCCESS';

export const DELETE_COMMENT = '@@app/DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = '@@app/DELETE_COMMENT_SUCCESS';
