export const INITIALIZE_ORGANIZATION = '@@app/INITIALIZE_ORGANIZATION';

export const UPDATE_ORGANIZATION = '@@app/UPDATE_ORGANIZATION';
export const CREATE_ORGANIZATION = '@@app/CREATE_ORGANIZATION';

export const UPDATE_ORGANIZATION_SUCCESS = '@@app/UPDATE_ORGANIZATION_SUCCESS';
export const CREATE_ORGANIZATION_SUCCESS = '@@app/CREATE_ORGANIZATION_SUCCESS';
