export const UPDATE_IMAGE = '@@app/UPDATE_IMAGE';
export const UPDATE_IMAGE_SUCCESS = '@@app/UPDATE_IMAGE_SUCCESS';
export const DELETE_IMAGE = '@@app/DELETE_IMAGE';
export const DELETE_IMAGE_SUCCESS = '@@app/DELETE_IMAGE_SUCCESS';
export const MAKE_IMAGE_PRIMARY = '@@app/MAKE_IMAGE_PRIMARY';
export const MAKE_IMAGE_PRIMARY_SUCCESS = '@@app/MAKE_IMAGE_PRIMARY_SUCCESS';
