export const FETCH_MATERIALS = '@@app/FETCH_MATERIALS';
export const FILE_MATERIAL = '@@app/FILE_MATERIAL';

export const FETCH_MATERIALS_SUCCESS = '@@app/FETCH_MATERIALS_SUCCESS';
export const FETCH_MATERIALS_ERROR = '@@app/FETCH_MATERIALS_ERROR';
export const FILE_MATERIAL_SUCCESS = '@@app/FILE_MATERIAL_SUCCESS';

export const DELETE_MATERIAL = '@@app/DELETE_MATERIAL';
export const DELETE_MATERIAL_SUCCESS = '@@app/DELETE_MATERIAL_SUCCESS';

export const DUPLICATE_MATERIAL = '@@app/DUPLICATE_MATERIAL';
export const DUPLICATE_MATERIAL_SUCCESS = '@@app/DUPLICATE_MATERIAL_SUCCESS';
