export const FETCH_MATERIALS = 'FETCH_MATERIALS';
export const FETCH_MATERIALS_SUCCESS = 'FETCH_MATERIALS_SUCCESS';
export const FETCH_MATERIALS_ERROR = 'FETCH_MATERIALS_ERROR';

export const CREATE_MATERIAL = 'CREATE_MATERIAL';
export const FILE_MATERIAL = 'FILE_MATERIAL';
export const CREATE_MATERIAL_SUCCESS = 'CREATE_MATERIAL_SUCCESS';
export const FILE_MATERIAL_SUCCESS = 'FILE_MATERIAL_SUCCESS';

