export const FETCH_PROJECTS = '@@app/FETCH_PROJECTS';
export const FETCH_PROJECTS_SUCCESS = '@@app/FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_ERROR = '@@app/FETCH_PROJECTS_ERROR';

export const CREATE_PROJECT = '@@app/CREATE_PROJECT';
export const CREATE_PROJECT_SUCCESS = '@@app/CREATE_PROJECT_SUCCESS';

export const DELETE_PROJECT = '@@app/DELETE_PROJECT';
export const DELETE_PROJECT_SUCCESS = '@@app/DELETE_PROJECT_SUCCESS';

export const FILE_PROJECT = '@@app/FILE_PROJECT';
export const FILE_PROJECT_SUCCESS = '@@app/FILE_PROJECT_SUCCESS';

export const DUPLICATE_PROJECT = '@@app/DUPLICATE_PROJECT';
export const DUPLICATE_PROJECT_SUCCESS = '@@app/DUPLICATE_PROJECT_SUCCESS';
